### CREATE USER
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "Boss",
  "age": 40,
  "email": "boss123@test.com",
  "password": "1234"
}

### LOGIN USER
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "boss123@test.com",
  "password": "1234"
}

### GET USERS
GET http://localhost:8080/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJib3NzMTIzQHRlc3QuY29tIiwiaWF0IjoxNzcxOTY4MTgxLCJleHAiOjE3NzIwNTQ1ODF9.bsltkH51zs0d5HRMWl3e8BiCHrL5VK_qM2Zh8XrkgTo